# Базы Данных
# Домашнее задание №6 по теме "Подзапросы"

SQL-запросы можно выполнять непосредственно в данном ноутбуке. Для этого в следующем параграфе заполните переменные `your_login` и `your_pass` и запустите остальные ячейки.

Логин / пароль можно получить с помощью ресурса [self-service](https://self-service.culab.ru/).

Если в google-colab код не запускается, можно воспользоваться ресурсом [jupyter.culab.ru](https://jupyter.culab.ru).

В данном домашнем задании необходимо писать SQL-запросы к схеме `db_vzhukh` - учебной базе сети дарксторов быстрой доставки «Вжух».

Схема и часовой пояс `Europe/Moscow` задаются прямо в подключении, поэтому имена таблиц можно писать без префикса схемы, а время в столбцах типа `timestamptz` показывается по Москве.

Если писать запросы в IDE, то можно воспользоваться командой `SET search_path = db_vzhukh, public;`, чтобы зафиксировать схему. Также можно вопользоваться командой `SET timezone = 'Europe/Moscow';` чтобы зафиксировать timezone.

In [ ]:
# Используйте свой логин и пароль
your_login = 'cu_dev_db'
your_pass = '0bc78ae1793a09559c3d57ac3d0e2841' # так уж и быть, на этот раз пароль не уберу)
# короче по итогу я использовал локальный клон той бд ибо цулаб умер(

In [ ]:
import pandas as pd
import psycopg2  # noqa: F401
from sqlalchemy import create_engine, event

engine = create_engine(
  f"postgresql+psycopg2://{your_login}:{your_pass}@cu-dev-db.iamamaev.ru:5432/cu_dev_db?sslmode=require",
  connect_args={
      "options": "-csearch_path=db_vzhukh,public -ctimezone=Europe/Moscow"
  },
)

@event.listens_for(engine, "connect")
def set_search_path(dbapi_conn, conn_record):
    """У меня стоит pgbouncer перед базой данных, так что connect_args из темплейта дропались"""
    cur = dbapi_conn.cursor()
    cur.execute("SET search_path TO db_vzhukh, public")
    cur.execute("SET timezone TO 'Europe/Moscow'")
    cur.close()
    dbapi_conn.commit()

def execute_sql(query):
    conn = engine.raw_connection()
    try:
        cursor = conn.cursor()
        cursor.execute(query)
        conn.commit()

        # вывод сообщений PL/pgSQL (только RAISE NOTICE)
        if conn.notices:
            print("PostgreSQL messages:")
            for notice in conn.notices:
                print(" ", notice.strip())
            conn.notices.clear()

        # DQL
        if cursor.description is not None:
            columns = [desc[0] for desc in cursor.description]
            rows = cursor.fetchall()
            return pd.DataFrame(rows, columns=columns)

        # DDL / DML
        if cursor.rowcount != -1:
            print(f"Command executed successfully, affected rows: {cursor.rowcount}")
        else:
            print("Command executed successfully")

        return None

    except Exception as e:  # noqa: BLE001
        conn.rollback()
        print("Error:", e)
    finally:
        cursor.close()
        conn.close()

In [15]:
# Проверка успешности подключения

query = """
select *
from darkstore
limit 5;
"""
execute_sql(query)

,darkstore_id,city_id,name,address,opened_dt,closed_dt
0,1,1,Тимирязевская,"г. Москва, ул. Дубки, д. 7",2024-03-12,None
1,2,1,Академическая,"г. Москва, ул. Профсоюзная, д. 21к2",2024-08-01,None
2,3,2,Петроградская,"г. Санкт-Петербург, ул. Ленина, д. 34",2024-05-20,None
3,4,2,Купчино,"г. Санкт-Петербург, Будапештская ул., д. 11",2025-02-10,None
4,5,3,Уралмаш,"г. Екатеринбург, ул. Машиностроителей, д. 4",2025-04-05,None

На семинаре ты отвечал на вопросы коллег из сети дарксторов «Вжух» с помощью подзапросов и общих табличных выражений. В домашнем задании пять новых вопросов: от закупок, службы качества, логистики и категорийного менеджера. Первые три задания решаются подзапросами, последние два - общими табличными выражениями: несколько выражений в одном `WITH` и рекурсивный `WITH`.

## Задача 1. [2 балла]

Закупки проверяют, по какой цене товары продавались в августе. Нужны позиции заказов, созданные с 1 августа 2026 года, цена которых выше средней цены продажи этого же товара за всё время.

Выведи `order_id`, `sku_id` и `price`. Среднюю цену товара посчитай коррелированным подзапросом в `WHERE`. Статус заказа не учитывай ни в выборке, ни в среднем: нужны все позиции из `order_item`. Отсортируй по `order_id`, затем по `sku_id`.

In [16]:
# Ответ:
query = """
select oi.order_id, oi.sku_id, oi.price
from order_item oi
         join orders o on o.order_id = oi.order_id
where o.created_at >= '2026-08-01'
  and oi.price > (select avg(oi2.price)
                  from order_item oi2
                  where oi2.sku_id = oi.sku_id)
order by oi.order_id, oi.sku_id;
"""
execute_sql(query)

   order_id  sku_id   price
0        18      15  672.00
1        18      20  184.80
2        25      20  184.80
3        32      15  672.00
4        32      30  599.20

## Задача 2. [2 балла]

Служба качества проверяет доставку товаров с возрастным ограничением: курьер должен был посмотреть документ покупателя. Нужен список заказов в любом статусе, в которых есть хотя бы один такой товар.

Возрастное ограничение записано в столбце `product.min_age`, у обычных товаров там 0. Выведи `order_id`, `darkstore_id` и `courier_id` заказов. Используй `EXISTS`. Отсортируй по `order_id`.

In [17]:
# Ответ:
query = """
select o.order_id, o.darkstore_id, o.courier_id
from orders o
where exists (select 1
              from order_item oi
                       join product p on p.sku_id = oi.sku_id
              where oi.order_id = o.order_id
                and p.min_age > 0)
order by o.order_id;
"""
execute_sql(query)

   order_id  darkstore_id  courier_id
0         4             1           4
1        29             3          12
2        33             4          16
3        42             5          20

## Задача 3. [2 балла]

Логистика распределяет курьеров на следующий месяц и хочет знать, кто из них возит больше остальных. Нужны работающие курьеры, у которых заказов больше, чем в среднем на одного работающего курьера. Курьеры в таблице `employee` отмечены значением `role = 'courier'`. У уволенного курьера заполнен столбец `employee.dismissed_dt`. Заказы считай в любом статусе.

Выведи `employee_id`, `full_name` и `darkstore_id`. Число заказов курьера и среднее по курьерам посчитай подзапросами в `WHERE`. Уволенных курьеров исключи в двух местах: в основной выборке, чтобы они не попали в список, и при подсчёте среднего, чтобы их заказы не попали в расчёт. Заказы без назначенного курьера в среднем не учитывай. Отсортируй по `employee_id`.

In [18]:
# Ответ:
query = """
select e.employee_id, e.full_name, e.darkstore_id
from employee e
where e.role = 'courier'
  and e.dismissed_dt is null
  and (select count(*)
       from orders o
       where o.courier_id = e.employee_id)
      > (select count(o.order_id)::numeric / count(distinct c.employee_id)
         from employee c
                  left join orders o on o.courier_id = c.employee_id
         where c.role = 'courier'
           and c.dismissed_dt is null)
order by e.employee_id;
"""
execute_sql(query)

   employee_id                 full_name  darkstore_id
0            3   Мельников Илья Петрович             1
1            9  Абдулов Руслан Маратович             2
2           12   Шарипов Азат Ильдарович             3
3           16    Пахомов Кирилл Юрьевич             4

## Задача 3. [2 балла]

Закупки готовят дозаказ на следующую неделю и ищут, где на складах заканчиваются популярные товары.

Популярным считается товар, который попал больше чем в пять заказов. Заказы считай по всем строкам `order_item`, статус заказа не учитывай. Товар заканчивается, если его свободный остаток в дарксторе меньше 20 единиц. Свободный остаток - это `qty_available` минус `qty_reserved` из таблицы `stock`.

Объяви в одном `WITH` два выражения через запятую. Первое, `product_orders`, считает число заказов по каждому товару. Второе, `low_stock`, выбирает из `stock` строки со свободным остатком меньше 20. Основной запрос соединяет оба выражения между собой и с таблицей `product`. Выведи `darkstore_id`, `sku_id`, название товара, свободный остаток в столбце `free_quantity` и число заказов в столбце `orders_count`. Отсортируй по `darkstore_id`, затем по `sku_id`.

In [19]:
# Ответ:
query = """
with product_orders as (select sku_id, count(distinct order_id) as orders_count
                        from order_item
                        group by sku_id),
     low_stock as (select darkstore_id, sku_id, qty_available - qty_reserved as free_quantity
                   from stock
                   where qty_available - qty_reserved < 20)
select ls.darkstore_id, ls.sku_id, p.name, ls.free_quantity, po.orders_count
from low_stock ls
         join product_orders po on po.sku_id = ls.sku_id
         join product p on p.sku_id = ls.sku_id
where po.orders_count > 5
order by ls.darkstore_id, ls.sku_id;
"""
execute_sql(query)

,darkstore_id,sku_id,name,free_quantity,orders_count
0,1,8,"Яйцо куриное С0, 10 шт",16,6
1,1,16,"Голубика, 125 г",10,6
2,1,40,"Батончик протеиновый, 40 г",16,6
3,2,40,"Батончик протеиновый, 40 г",16,6
4,3,20,"Укроп свежий, 50 г",9,8
5,4,19,Картофель мытый,13,6
6,4,20,"Укроп свежий, 50 г",15,8
7,5,30,"Борщ с говядиной, 400 г",18,6

## Задача 4. [2 балла]

Закупки проверяют, по какой цене товары продавались в августе. Нужны позиции заказов, созданные с 1 августа 2026 года, цена которых выше средней цены продажи этого же товара за всё время.

Выведи `order_id`, `sku_id` и `price`. Среднюю цену товара посчитай коррелированным подзапросом в `WHERE`. Статус заказа не учитывай ни в выборке, ни в среднем: нужны все позиции из `order_item`. Отсортируй по `order_id`, затем по `sku_id`.

In [20]:
# Ответ:
query = """
select oi.order_id, oi.sku_id, oi.price
from order_item oi
         join orders o on o.order_id = oi.order_id
where o.created_at >= '2026-08-01'
  and oi.price > (select avg(oi2.price)
                  from order_item oi2
                  where oi2.sku_id = oi.sku_id)
order by oi.order_id, oi.sku_id;
"""
execute_sql(query)

   order_id  sku_id   price
0        18      15  672.00
1        18      20  184.80
2        25      20  184.80
3        32      15  672.00
4        32      30  599.20

## Задача 5. [2 балла]

Категорийный менеджер направления «Молочное и яйца» (`category_id = 1`) просит список всех товаров направления. Товары привязаны к вложенным категориям, у самой категории 1 товаров нет. Вложенная категория хранит номер родительской в столбце `product_category.parent_category_id`.

Собери рекурсивным общим табличным выражением категорию 1 и все вложенные в неё категории на любой глубине. Затем соедини результат с таблицей `product`. Выведи `sku_id`, название товара и название категории в столбце `category_name`. Отсортируй по `sku_id`.

In [21]:
# Ответ:
query = """
with recursive cats as (select category_id, name
                        from product_category
                        where category_id = 1
                        union all
                        select pc.category_id, pc.name
                        from product_category pc
                                 join cats c on pc.parent_category_id = c.category_id)
select p.sku_id, p.name, c.name as category_name
from cats c
         join product p on p.category_id = c.category_id
order by p.sku_id;
"""
execute_sql(query)

   sku_id                            name      category_name
0       1    Молоко питьевое 3.2%, 900 мл    Молоко и сливки
1       2              Сливки 20%, 500 мл    Молоко и сливки
2       3              Кефир 2.5%, 900 мл    Молоко и сливки
3       4                  Сыр Российский               Сыры
4       5  Сыр Моцарелла в рассоле, 125 г               Сыры
5       6      Йогурт греческий 2%, 130 г  Йогурты и десерты
6       7       Творожок ванильный, 100 г  Йогурты и десерты
7       8          Яйцо куриное С0, 10 шт               Яйца